version: "3.7"
services:
    # image project
    api:
        build: 
            args: 
                user: igor
                uid: 1001
            context: ./
            dockerfile: Dockerfile
        image: laravel-api-cache
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
            - queue
        networks: 
            - laravel-api-network
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 80:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-api-network

    # db mysql
    mysql:
        image: mysql:8.0.20
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - mysqldbvolume:/var/lib/mysql
        ports: 
            - 3306:3306
        networks: 
            - laravel-api-network

    # queue
    queue:
        build: 
            args: 
                user: igor
                uid: 1001
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel-api-network

    # redis
    redis:
        image: redis:latest
        networks: 
            - laravel-api-network

networks: 
    laravel-api-network:
        driver: bridge

# Volume
volumes:
  mysqldbvolume:
    driver: local